import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'

const divStyle = {
  color: 'blue'
};

export default function Home() {

  const [fixtures, setFixtures] = useState(null)
  const [isLoading, setLoading] = useState(false)
  useEffect(() => {
    setLoading(true)
    fetch('https://balti-football-api.web.app/api/fixtures')
      .then((res) => res.json())
      .then((data) => {
      
        setFixtures(data.fixtures)
        setLoading(false)
          
      })
  }, [])
 
  if (isLoading) return <p>Loading...</p>
  if (!fixtures) return <p>No profile data</p>

  let mygames = Array.from(fixtures);
  console.log('mygames ' + typeof mygames)
  mygames.map((game)=>{
    console.log(game);
  })
  console.log(mygames.length);
  const fixturesList = mygames.map((fix,index) =>
    <ListItem key={index} value={fix.HOME}></ListItem>
  )

  const numbers = [1, 2, 3, 4, 5];
  console.log('numbers ' + typeof numbers)
  const listItems = numbers.map((number,index) =>
    <ListItem key={index} value={number}></ListItem>
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Balti Sports FC</h1>
        <ul>
          {listItems}
        {fixturesList}
        </ul>
      </main>
    </div>
  )
}

function ListItem(props) {
  return <li>{props.value}</li>;
}
