import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Home() {
  const [results, setResults] = useState([])
  const [isLoadingResults, setLoadingResults] = useState(false)
  const [fixtures, setFixtures] = useState([])
  const [isLoadingFixtures, setLoadingFixtures] = useState(false)
  const [leagueTable, setLeagueTable] = useState([])
  const [isLoadingLeagueTable, setLoadingLeagueTable] = useState(true)
  useEffect(() => {
    fetchData();
    async function fetchData() {
      setLoadingFixtures(true);
      const result = await fetch('https://balti-football-api.web.app/api/fixtures');
      const resultsData = await result.json()
      setFixtures(resultsData.fixtures);
      setLoadingFixtures(false);

      setLoadingFixtures(true);
      const fixturesResponse = await fetch('https://balti-football-api.web.app/api/results')
      const fixturesData = await fixturesResponse.json();
      setResults(fixturesData.results);
      setLoadingResults(false);

      const tableResponse = await fetch('https://balti-football-api.web.app/api/table')
      const tableData = await tableResponse.json();
      let table = tableData.table;
      table.shift();
      console.log(table);
      setLeagueTable(table);
      setLoadingLeagueTable(false);
    }
  }, [])

  const loadingFixtursMessage = isLoadingFixtures ? <p>loading fixtures</p> : '';
  const loadingResultsMessage = isLoadingResults ? <p>loading results</p> : '';
  const loadingLeagueTableMessage = isLoadingLeagueTable ? <p>loading league table</p> : '';

  const fixturesList = fixtures.map((fix, index) =>
    <Fixture key={index} home={fix.HOME} away={fix.AWAY} date={fix.DATE}></Fixture>
  )

  const resultsList = results.map((res, index) =>
    <Result key={index} home={res.HOME} away={res.AWAY} date={res.DATE} score={res.SCORE}></Result>
  )

  const leagueTableRows = leagueTable.map((res, index) => {
    return <LeagueTableRow key={index} position={res.POSITION} club={res.CLUB} played={res.PLAYED} won={res.WON} drawn={res.DRAWN} lost={res.LOST} goalDiff={res.GOAL_DIFFERENCE} points={res.POINTS}></LeagueTableRow>;
  })

  return (
    <div>
      <Head>
        <title>Create Next App2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='manifest' href='/manifest.json' />
      </Head>

      <main>
        <div className="container mx-auto px-4">
          <h1 className="font-medium leading-tight text-3xl mt-0 mb-2 text-blue-600">Balti Sports FC</h1>



          <h2 className="font-medium leading-tight text-xl mt-0 mb-2 text-blue-600">Fixtures</h2>
          {loadingFixtursMessage}
          {fixturesList}
          <h2 className="font-medium leading-tight text-xl mt-0 mb-2 text-blue-600">Recent results</h2>
          {loadingResultsMessage}
          {resultsList}
          <h2 className="font-medium leading-tight text-xl mt-0 mb-2 text-blue-600">League table</h2>
          {loadingLeagueTableMessage}
          <table className="w-full text-left text-gray-500 dark:text-gray-400">
            <thead className="text-gray-700 bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" className="py-2 px-3">Pos</th>
                <th scope="col" className="py-2 px-3">Club</th>
                <th scope="col" className="py-2 px-3">Pl</th>
                <th scope="col" className="py-2 px-3">W</th>
                <th scope="col" className="py-2 px-3">D</th>
                <th scope="col" className="py-2 px-3">L</th>
                <th scope="col" className="py-2 px-3">GD</th>
                <th scope="col" className="py-2 px-3">Points</th>
              </tr>
            </thead>
            <tbody className="bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              {leagueTableRows}
            </tbody>

          </table>
        </div>
      </main>
    </div>

  )
}

function Fixture({ home, away, date }) {
  return <div className="display-large">{date} - {home} <span style={{ 'fontWweight': '300' }}>versus</span> {away}</div>;
}

function Result({ home, away, date, score }) {
  return <div className="display-large">{date} - {home} <span style={{ 'fontWeight': '700' }}>{score}</span> {away}</div>;
}

function LeagueTableRow({ position, club, played, won, drawn, lost, goalDiff, points }) {
  return <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
    <td className="py-2 px-3">{position}</td>
    <td className="py-2 px-3">{club}</td>
    <td className="py-2 px-3">{played}</td>
    <td className="py-2 px-3">{won}</td>
    <td className="py-2 px-3">{drawn}</td>
    <td className="py-2 px-3">{lost}</td>
    <td className="py-2 px-3">{goalDiff}</td>
    <td className="py-2 px-3"> {points}</td>
  </tr>;
}